-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
  output = "DP-2",
  mode = "2560x1440@165",
  position = "2560x0",
  scale = "1",
  vrr = 1,
})

hl.monitor({
  output = "HDMI-A-2",
  mode = "2560x1440",
  position = "0x0",
  scale = "1",
})

-- monitor=HDMI-A-2, 1920x1080, 5120x0, 1
hl.monitor({
  output = "HDMI-A-1",
  disabled = true,
})

-- See https://wiki.hyprland.org/Configuring/Keywords/ for more

-- Execute your favorite apps at launch
-- Source a file (multi-file configs)
-- source = ~/.config/hypr/myColors.conf

-- Set programs that you use
local terminal = "alacritty"
local fileManager = "thunar"
local menu = "/home/jole/.config/rofi/launchers/type-6/launcher.sh"

-- Some default env vars.
hl.env("XCURSOR_SIZE", "24")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("WLR_NO_HARDWARE_CURSORS", "1")
hl.env("XDG_SESSION_TYPE", "wayland")

hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.animation({
  leaf = "windows",
  enabled = true,
  speed = 5,
  bezier = "myBezier",
})
hl.animation({
  leaf = "windowsOut",
  enabled = true,
  speed = 5,
  bezier = "default",
  style = "popin 80%",
})
hl.animation({
  leaf = "border",
  enabled = true,
  speed = 10,
  bezier = "default",
})
hl.animation({
  leaf = "borderangle",
  enabled = true,
  speed = 8,
  bezier = "default",
})
hl.animation({
  leaf = "fade",
  enabled = true,
  speed = 7,
  bezier = "default",
})
hl.animation({
  leaf = "workspaces",
  enabled = true,
  speed = 6,
  bezier = "default",
})

hl.window_rule({
  name = "windowrule-1",
  match = {
    class = "^(kitty)$",
  },
  opacity = 0.9,
})

hl.window_rule({
  name = "windowrule-2",
  match = {
    class = "^(thunar)$",
  },
  opacity = 0.8,
})

hl.window_rule({
  name = "windowrule-3",
  match = {
    class = "^(Code)$",
  },
  opacity = "1 0.9",
})

hl.window_rule({
  name = "windowrule-4",
  match = {
    class = "^(Alacritty)$",
  },
  opacity = 0.8,
})

hl.window_rule({
  name = "windowrule-5",
  match = {
    class = "^(dev.zed.Zed)$",
  },
  opacity = 0.8,
})

hl.window_rule({
  name = "windowrule-6",
  match = {
    class = "^(obsidian)$",
  },
  opacity = 0.8,
})

local mainMod = "SUPER"

hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + C", hl.dsp.window.close())
hl.bind(mainMod .. " + M", hl.dsp.exit())
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mainMod .. " + A", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
hl.bind(mainMod .. " + G", hl.dsp.exec_cmd("grim -g \"$(slurp)\""))
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("ghostty -e yazi"))
hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + h", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + l", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + k", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + j", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

hl.bind(mainMod .. " + T", hl.dsp.workspace.swap_monitors({ monitor1 = "0", monitor2 = "1" }))
hl.bind(mainMod .. " + X", hl.dsp.window.move({ monitor = "+1" }))

hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1.4 @DEFAULT_AUDIO_SINK@ 2%+"), { repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1.4 @DEFAULT_AUDIO_SINK@ 2%-"), { repeating = true })

hl.bind(mainMod .. " + Z", hl.dsp.exec_cmd("hyprlock"))
hl.bind(mainMod .. " + O", hl.dsp.exec_cmd("wlogout"))
hl.config({
  input = {
    kb_layout = "de",
    kb_variant = "",
    kb_model = "",
    kb_options = "",
    kb_rules = "",
    numlock_by_default = true,
    follow_mouse = 1,
    touchpad = {
      natural_scroll = false,
    },
    sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
  },
  general = {
    -- See https://wiki.hyprland.org/Configuring/Variables/ for more
    gaps_in = 5,
    gaps_out = 15,
    border_size = 2,
    col = {
      active_border = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
      inactive_border = "rgba(595959aa)",
    },
    layout = "dwindle",
    -- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = true,
  },
  decoration = {
    -- See https://wiki.hyprland.org/Configuring/Variables/ for more
    rounding = 10,
    blur = {
      enabled = true,
      size = 10,
      passes = 3,
    },
  },
  animations = {
    enabled = true,
    -- Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
  },
  dwindle = {
    -- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    preserve_split = true, -- you probably want this
  },
  misc = {
    -- See https://wiki.hyprland.org/Configuring/Variables/ for more
    force_default_wallpaper = 0, -- Set to 0 to disable the anime mascot wallpapers
  },
  -- Example per-device config
  -- Example windowrule v1
  -- windowrule = float, ^(kitty)$
  -- Example windowrule v2
  -- windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
  -- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
  -- windowrulev2 = opacity 0.8,class:^(com.mitchellh.ghostty)$
  -- See https://wiki.hyprland.org/Configuring/Keywords/ for more
  -- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
  -- Move focus with mainMod + arrow keys
  -- Switch workspaces with mainMod + [0-9]
  -- Move active window to a workspace with mainMod + SHIFT + [0-9]
  -- Example special workspace (scratchpad)
  -- Scroll through existing workspaces with mainMod + scroll
  -- Move/resize windows with mainMod + LMB/RMB and dragging
  -- volume keys bind
  -- bind for hyprlock and wlogout
})

hl.on("hyprland.start", function()
  hl.exec_cmd("waybar & hyprpaper & dunst")
  hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
  hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
end)
