preload = /home/jole/Pictures/Aenami/mountain_sunset.jpg

wallpaper {
    monitor = DP-2
    path = /home/jole/Pictures/Aenami/mountain_sunset.jpg
    fit_mode = cover
}
wallpaper {
    monitor = HDMI-A-2
    path = /home/jole/Pictures/Aenami/mountain_sunset.jpg
    fit_mode = cover
}
#enable splash text rendering over the wallpaper
splash = false 

